### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by Echuir** [kauffman12/EQLogParser#102]
Can we have it so we can select any Windows installed font? Also add Font shadows or have it always on, or even just a 1 or 2 pixel outline.

**Comment by Echuir** [comment]
Also add Font shadows or have it always on, or even just a 1 or 2 pixel outline.

**Comment by kauffman12** [comment]
Is this mainly for the text overlay or everything?

**Comment by CrzyHlfAzn** [comment]
It would be nice for the text overlay.

**Comment by kauffman12** [comment]
In 2.1.29 the Text Overlay has an option for Font Family and drop shadow is added by default. There's option to turn that off at the moment but later on I may add more choices.

The app also has some font settings under Options -> Look and Feel. I can't add everything due to some things not sizing too well so I'm just going with a set of common fonts that work well.
