### ISSUE TITLE
Variables for timers

### ISSUE THREAD

**Issue by Johnm13tx** [kauffman12/EQLogParser#108]
timers seem to have to be static, without an ability to create dynamic ones based on the trigger text unless I'm missing something, ie:

(Bob.*|Jim*|You) tells the raid, '{N} Seconds'

**Comment by kauffman12** [comment]
Is N always counted in seconds?

**Comment by Johnm13tx** [comment]
yes, the trigger is always seconds, thru GINA can convert to MM:SS but it's not necessary for that to happen.

**Comment by kauffman12** [comment]
Looking at the GINA docs. This is the {TS} tag right and not actually {N}?

**Comment by Johnm13tx** [comment]
yes, but EQlp recognizes {N} as the numerical value for alternate timer name, text overlay, etc, so was using that for trigger testing

**Comment by esr-sudo** [comment]
If I understand this conversation correctly, it looks like the {TS} variable, ?! exclusions, and grouping  via (pattern1|pattern2) is not supported.

It is a bit janky, but it would be cool if similar functionality could be added for this in EQLP.  I'd love to migrate solely over to EQLP instead of using both.
(This is triggered in game by hitting a hotkey for /inspectbuffs mine
pattern:

--You sense (?!Bone-Rattling Shriek|Dead Mesmerization VI|Energy Sap|Scent|Howl of Tashan|Rot Vulnerability|Pestilent Paralysis|Immobilize|Spine-Chilling Shriek|Voidwhisper Manacles){s1}( Rk\. III?)? \[{C}\] on {s2} has {TS} remaining\.--$

timer name:
{S1} on {S2}

**Comment by kauffman12** [comment]
Okay try this in 2.1.35. Also in esr-sudo's example the [ needs to be escaped.

This should work:

--You sense (?!Bone-Rattling Shriek|Dead Mesmerization VI|Energy Sap|Scent|Howl of Tashan|Rot Vulnerability|Pestilent Paralysis|Immobilize|Spine-Chilling Shriek|Voidwhisper Manacles){s1}( Rk. III?)? \[{C}\] on {s2} has {TS} remaining.--$

**Comment by kauffman12** [comment]
I guess github is removing the escape characters. Here I'll try again using code blocks.

`--You sense (?!Bone-Rattling Shriek|Dead Mesmerization VI|Energy Sap|Scent|Howl of Tashan|Rot Vulnerability|Pestilent Paralysis|Immobilize|Spine-Chilling Shriek|Voidwhisper Manacles){s1}( Rk. III?)? \[{C}\] on {s2} has {TS} remaining.--$`

**Comment by esr-sudo** [comment]
Wow, very excited to see that in the patch note!   Looking forward to giving it a try.

**Comment by esr-sudo** [comment]
I have not fully tested it...but....it works!  In order for this janky timer to be usable and not completely obtrusive (ie: where it will fall off automatically, or can be manually cleared if needed)  it needs more than 2 end early conditions, but this works if put into just one of them:

`(^Your {S1} spell on {S2} has been overwritten|^{s2} has been slain|^You have slain {s2}|^{C} tells you, 'clear dot timers'|^{C} tells you, 'end all timers'|^Your {S1} spell has worn off of {S2})`

**Comment by kauffman12** [comment]
Yeah I've been avoiding adding an endless amount of patterns. I figure people doing complex stuff to need more than 1 or 2 can probably figure out a fancy regex.
