### ISSUE TITLE
 {repeated} only has functionality with a timer

### ISSUE THREAD

**Issue by viruleq** [kauffman12/EQLogParser#111]
Would be nice if repeated worked in a text overlay for beams and other such AE abilities.

**Comment by kauffman12** [comment]
I did add support for this to text overlays n 2.1.40 and I'm converting any use of {counter} to {repeated} since they are close enough to each other. Although, I do think it makes more sense to use this in a timer as you can set those to restart the current timer and it doesn't just spam like a text window.
