### ISSUE TITLE
Phonetic pronunciation

### ISSUE THREAD

**Issue by Vanesty** [kauffman12/EQLogParser#130]
a nice feature would be to add a phonetic pronouncement to the voice feature. character names seem to always be pronounced wrong.

**Comment by Ahamay** [comment]
I also would love a Character name phonetic pronounciation feature like GINA had.

**Comment by kauffman12** [comment]
Yeah I'll probably add a table so you can add as many mappings as you want for any word. You'll just have to figure out the microsoft phonetic alphabet if you really want it to sound right.

**Comment by kauffman12** [comment]
So it turns out all the cool features aren't really useful so all I could do was add a simple replacement. You specify the word you want to replace and the text to replace it with. Hopefully that's enough because all I can really do. So, try 2.1.57 and the Phonetic Dictionary option in Trigger Manager.

**Comment by Vanesty** [comment]
Thank you

**Comment by kauffman12** [comment]
No prob.
