### ISSUE TITLE
Parser keeps labeling me as a Mage

### ISSUE THREAD

**Issue by Warderkembal** [kauffman12/EQLogParser#18]
I'm a ranger playing on Thornblade currently. The parse just tells me I'm a mage. These are the things I've tried:

https://www.reddit.com/r/everquest/comments/oyq8o8/eq_log_parser_help/

**Comment by kauffman12** [comment]
Well if it happens right away. You could delete your log and start a new
one. Then once it tells you that you're a mage just send me that log file.
I'll try it out.

Or if you don't want to send logs look at your spell counts and send me the
BB code version or screenshot. It tries to go by spells used to figure out
the class.

**Comment by Warderkembal** [comment]
[eqlog_Kembal_thornblade.txt](https://github.com/kauffman12/EQLogParser/files/6947452/eqlog_Kembal_thornblade.txt)

**Comment by Warderkembal** [comment]
I posted my logs but after thinking it over and messing around. I come to realize the first thing I do is click my Tolan's Bracer (Summon Arrows) because we aren't in Luclin yet. And because rangers share so many spells at this point in the game it can't figure out what I am. I just hit something with Call of Flame and it pulled me right up as a ranger.

**Comment by kauffman12** [comment]
Ah ok. Yeah, that's what's happening for sure. And if you summon arrows one
time but then cast something like call of flame a bunch of times. It should
switch you from mage to ranger. It doesn't just pick the first one it sees.

Although, I could start adding some other checks that override the spells.
Like I see you have:
[Thu Aug 05 15:55:56 2021] You shoot a lion patriarch for 69 points of
damage. (Double Bow Shot)

Maybe for melee it makes sense to look for Double Bow Shot, Slay Undead,
Decap. etc and let them override whatever the current class is. I can put
in something like that pretty quickly I think and also Eye of Veeshan was
being ignored like all other eyes since people kill them for various
reasons. Check tonight or tomorrow for a new version.

**Comment by kauffman12** [comment]
Re-open if this keeps happening.
