### ISSUE TITLE
Feature request - backup feature enhancements

### ISSUE THREAD

**Issue by BronsonMagnan** [kauffman12/EQLogParser#193]
The backup feature is great but it has a few usability problems
1. the file name is always the same, maybe automatically append yyyyMMdd-HHmmss to the file so we don't have naming conflicts with older backups (stuff the eqlp version number into one of the metadata values on the file)
2. i will forget to use it, often enough to be relevant.
3. maybe add an option to take backups on a schedule, and possible an option to automatically run when receiving a share from another user.
4. add an option to execute it before launching the update from inside the app.
5. maybe add a command line option to the executable so I can just run 'EQLogParser.exe /backup:<path>' from a scheduled task that triggers on user logon.

**Comment by kauffman12** [comment]
The default filename has version and date/month plus millis to add some randomness. Backing up by the hour seems excessive. Really you shouldn't need to backup very often. I only added it because some people were asking how to move their settings to a new PC. When upgrading the trigger DB next time I'll make a separate of that file but that won't be any time soon.

There's also a BackupUtil.exe now you can use if you want to schedule something yourself. Give it --path to where you want the backup to go. Use quotes if there's spaces in the path.  Something like:  BackupUtil --path "c:\my folder\backups" and it does the same backup process without prompting.
