### ISSUE TITLE
Difficulty with {N>y} 

### ISSUE THREAD

**Issue by esr-sudo** [kauffman12/EQLogParser#223]
{N=y} works just fine, but I try to use {N>y} and it doesn't seem to be working.

Match pattern:
`^You have gained an ability point\! You now have {N>100}`

Sound/text to speak:
`Spend AA {N}`

**Comment by kauffman12** [comment]
I think the problem is that in the real log message there are 2 spaces between the sentences. It worked for me when I created an example using the trigger tester but then when I copied an example from my log file it didn't work because of the spaces issue. Use this:

`^You have gained an ability point\!  You now have {N>100}`

**Comment by esr-sudo** [comment]
o
m
g

I feel dumb.   Thanks!

**Comment by kauffman12** [comment]
No prob.
