### ISSUE TITLE
Help cannot be read unless Microsoft Word license is activated

### ISSUE THREAD

**Issue by fgiraffe** [kauffman12/EQLogParser#229]
Choosing "Using Trigger Variables" or "Release Notes" from the Help menu launches Microsoft Word.
If you do not own a an active MS Word license, you cannot view these files.

**Comment by kauffman12** [comment]
That's because at some point you associated files with the .RTF extension with Microsoft Word.

1. Go through file explorer to:  C:\Program Files\EQLogParser\data
2. Right-click on releasenotes.rtf and choose Properties.
3. Click the Change button where it says that Word is being used to 'Open with'.
4. Then after the Change dialog comes up look for WordPad and select that as the default app.

WordPad is the usual default. Maybe certain PCs come setup to use Word but I'm not sure.

**Comment by fgiraffe** [comment]
I'm mortified, sorry to post an issue over something so trivial. 
Maybe my Win 11 cames like that out of the box?

**Comment by fgiraffe** [comment]
Closed, user error.

**Comment by kauffman12** [comment]
You never know. It wouldn't surprise me if some PCs come setup that way to get people to buy Office.
