### ISSUE TITLE
Request: Condensed Parse copy to clipboard for in game pasting

### ISSUE THREAD

**Issue by AndrewDHokie** [kauffman12/EQLogParser#37]
Would you be willing to change the current, or add new, functionality to copy parses so they can be better pasted in-game?

There are only a limited number of characters we can copy-paste to chat.

For example current:

Shei Vinitras in 777s, 18.05B Damage @23.23M, 16. BardName+Pets = 496.81M@641.04K in 775s | 17. SKName +Pets = 490.93M@631.83K in 777s {HD}

For a quick post into the game for those that do not parse could we have this shrunk down something like this:

Shei Vinitras 777s @23.23M | BardName 641.04K | SKName  631.83K | etc

This would allow us to give a quick parse for the top 15-19 people vs now we generally can just do the top 9.  (Obviously can repeat the process to get more but not optimal)

Thanks for the consideration.

**Comment by kauffman12** [comment]
The Parse Preview window lets you turn off time and showing specials. I could probably add an option for showing damage vs dps sometime soon.

**Comment by AndrewDHokie** [comment]
Thanks!

The ranking # and the +Pets comment adds a bunch of characters if you could maybe look at those also.

**Comment by kauffman12** [comment]
Try 1.8.71. Open Preview Parse at the bottom and turn off the check boxes for Denote Pets, Include Specials, Include Time, and Rank Players. Then if you want there's also an option to turn off DPS. 

I left damage as the only thing you need to see since it's the most important. DPS is kinda meaningless without time since someone that only lives for 10 seconds could have the highest DPS. So with all the above turned off and DPS you should be able to do 20 players most the time in order of who did the most.

**Comment by AndrewDHokie** [comment]
Very slick - Thanks  // Leaving DPS in there gets it to 18 is super!
