### ISSUE TITLE
Beastlord Bite of the Asp proc or cast?

### ISSUE THREAD

**Issue by JacLucFV** [kauffman12/EQLogParser#47]
I brought this up a while back.  For Beastlords, Bite of the Asp shows up as a spell proc, while Raven's Claw shows up as a spell cast.  They both work the same way, it just depends on which /autoskill the beastlord picks.  They both work the same way.  To me, all 3 of the autoskill AAs should show up as spell procs since we don't have to do anything to cast them except attack.  Bite of the Asp (from the Eagle Strike autoskill attack), Raven's Claw (From the Tiger Claw autoskill attack), and Gorilla Smash (from the Dragon Punch/Tail Rake autoskill) attack).

**Comment by kauffman12** [comment]
Ok I can fix that but all it will change is it won't show up in spell counts unless you check the box for showing procs. Is that all you were expecting? Since it doesn't have a unique damage line in the log. It's just counting the damage as a Strike in the breakdown. I might be able to parse that better in the future though. I feel like that might get complicated with other melee attacks.

[Sat Aug 06 15:13:06 2022] You begin casting Raven's Claw XXII.
[Sat Aug 06 15:13:06 2022] You strike Combat Dummy Beza for 523 points of damage.
[Sat Aug 06 15:13:06 2022] Combat Dummy Beza is clawed by a raven's claw!

**Comment by kauffman12** [comment]
This will be fixed in 2.0. Should be up sometime this week.
