### ISSUE TITLE
V2.0.0  Coloring from previous versions not in new version?

### ISSUE THREAD

**Issue by alabamr** [kauffman12/EQLogParser#48]
When looking at damage brekdown, all rows are just black instead of highlighting green like previous.  Not sure if intended but it seemed a lot easier to view when it was green, broke it up a bit.  Same thing in the normal damage summary, clicking the drop down for pets just shows in black while the previous version had it highlighted green.  If I choose "Save Summary (html)"  it still shows the green in the drop down when viewing it, just not in the program.  

![dmgbrk](https://user-images.githubusercontent.com/86625616/184515767-d3edd4f8-35f4-4ac5-8ad1-c5189dff3c5f.png)
![htmlsum](https://user-images.githubusercontent.com/86625616/184515769-16f3dcb8-0966-4594-9327-3bf601d67b9a.png)

**Comment by kauffman12** [comment]
The new version indents the rows and has that arrow to distinguish between the parent row and the others. I could add a color like this back if it makes it that much easier to read.

**Comment by alabamr** [comment]
Personally I liked the color, but will get used to it without it.  Thanks for all your work with this.

**Comment by kauffman12** [comment]
Ok no prob. I was thinking of adding a third theme that's similar to the old one. We'll see.

**Comment by kauffman12** [comment]
Been talking about some options for making the breakdown easier to read. Try 2.0.2 to see if this helps at all. Instead of combining everything into one level when you want to see procs, etc it now has another level to the tree.

![breakdown](https://user-images.githubusercontent.com/771335/184584448-05390a06-8aa9-4a30-b706-0e5bb953b186.png)
