### ISSUE TITLE
Request: improve the time duration UI

### ISSUE THREAD

**Issue by yeroca** [kauffman12/EQLogParser#79]
Another very minor issue:

It might just be me, but I find that the interface for setting the time duration in minutes and seconds a bit weird and not intuitive.

I'd prefer something where I could tab between the minutes and seconds, in a similar way to Gina's interface.

Either that or some method that feels more intuitive than the current one.

**Comment by kauffman12** [comment]
Instead of Tab this control uses arrow keys to move between the choices. Or to move left to right like Tabs you can use mouse clicks. For example, you can click in the minutes section. Type a number on they keyboard. Then click anywhere in the control to the right of the minutes and it moves to the seconds so you can continue typing.. Arrows let you go back and forth pretty easily as well. Type value. Arrow right. Type value, etc.

Now, I can probably listen for Tabs and make it move focus from left to right too just have another way to do it but personally I think clicking the mouse is even easier.

**Comment by yeroca** [comment]
Thanks, I'll play around with it some more based on your advice above.  You can wait to see if others comment as well.  It's just my impression that it isn't easy to figure out based on other UIs I have used, but of course that's a subjective thing.

**Comment by kauffman12** [comment]
Ok the new version should let you tab from left to right.

**Comment by yeroca** [comment]
I tried it out, and it works well

**Comment by kauffman12** [comment]
Cool
